import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { prisma } from '@/lib/prisma'

/**
 * POST /api/n8n/digest
 *
 * Call this from n8n to run an AI digest on meeting notes and get back
 * structured data + a formatted HTML email body.
 *
 * Body:
 * {
 *   "transcript": "Full meeting notes or transcript text",
 *   "title": "Meeting title (optional, defaults to 'Meeting')",
 *   "analystIds": ["id1", "id2"],   // optional — links meeting to analysts
 *   "saveMeeting": true,            // optional — saves the meeting to the DB
 *   "applyUpdates": true            // optional — writes digest results to DB (notes, moods, todos)
 * }
 *
 * Returns:
 * {
 *   "digest": { analystUpdates, projectUpdates, flags, todos },
 *   "emailHtml": "<html>...",
 *   "emailText": "plain text version",
 *   "meetingId": "..." (if saveMeeting: true)
 * }
 */

const MOOD_LABEL = { h: 'Thriving', m: 'Steady', l: 'Needs Attention' }

function buildEmailHtml(title, digest, date) {
  const d = new Date(date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })

  const flagsHtml = (digest.flags || []).length > 0 ? `
    <h2 style="color:#dc2626;font-size:16px;margin:24px 0 8px">⚠️ Flags</h2>
    <ul style="margin:0;padding-left:20px">
      ${digest.flags.map(f => `<li style="margin-bottom:6px;color:#374151">${f}</li>`).join('')}
    </ul>` : ''

  const todosHtml = (digest.todos || []).length > 0 ? `
    <h2 style="color:#1d4ed8;font-size:16px;margin:24px 0 8px">✅ Action Items</h2>
    <ul style="margin:0;padding-left:20px">
      ${digest.todos.map(t => `<li style="margin-bottom:6px;color:#374151">${t}</li>`).join('')}
    </ul>` : ''

  const analystHtml = (digest.analystUpdates || []).length > 0 ? `
    <h2 style="color:#374151;font-size:16px;margin:24px 0 8px">👥 Team Updates</h2>
    ${digest.analystUpdates.map(u => {
      const moodColor = u.mood === 'h' ? '#16a34a' : u.mood === 'l' ? '#dc2626' : '#6b7280'
      const moodLabel = MOOD_LABEL[u.mood] || ''
      return `<div style="background:#f9fafb;border-radius:8px;padding:12px 16px;margin-bottom:10px">
        <div style="font-weight:600;color:#111827">${u.name}${moodLabel ? ` <span style="font-size:12px;color:${moodColor};font-weight:400">(${moodLabel})</span>` : ''}</div>
        <div style="color:#374151;font-size:14px;margin-top:4px">${u.note}</div>
      </div>`
    }).join('')}` : ''

  const projectHtml = (digest.projectUpdates || []).length > 0 ? `
    <h2 style="color:#374151;font-size:16px;margin:24px 0 8px">📁 Project Updates</h2>
    ${digest.projectUpdates.map(u => `
      <div style="background:#f9fafb;border-radius:8px;padding:12px 16px;margin-bottom:10px">
        <div style="font-weight:600;color:#111827">${u.name}${u.status && u.status !== 'null' ? ` <span style="font-size:12px;color:#6b7280;font-weight:400">[${u.status}]</span>` : ''}</div>
        <div style="color:#374151;font-size:14px;margin-top:4px">${u.note}</div>
      </div>`).join('')}` : ''

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#111827">
  <div style="border-bottom:2px solid #e5e7eb;padding-bottom:16px;margin-bottom:8px">
    <h1 style="margin:0;font-size:22px;color:#111827">${title}</h1>
    <div style="color:#6b7280;font-size:14px;margin-top:4px">${d} · AI Meeting Digest</div>
  </div>
  ${flagsHtml}
  ${todosHtml}
  ${analystHtml}
  ${projectHtml}
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af">
    Generated by My Team Hub
  </div>
</body>
</html>`
}

function buildEmailText(title, digest, date) {
  const d = new Date(date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
  const lines = [`${title} — ${d}`, '']

  if ((digest.flags || []).length > 0) {
    lines.push('⚠️ FLAGS')
    digest.flags.forEach(f => lines.push(`  • ${f}`))
    lines.push('')
  }
  if ((digest.todos || []).length > 0) {
    lines.push('✅ ACTION ITEMS')
    digest.todos.forEach(t => lines.push(`  • ${t}`))
    lines.push('')
  }
  if ((digest.analystUpdates || []).length > 0) {
    lines.push('👥 TEAM UPDATES')
    digest.analystUpdates.forEach(u => {
      const mood = MOOD_LABEL[u.mood] ? ` (${MOOD_LABEL[u.mood]})` : ''
      lines.push(`  ${u.name}${mood}: ${u.note}`)
    })
    lines.push('')
  }
  if ((digest.projectUpdates || []).length > 0) {
    lines.push('📁 PROJECT UPDATES')
    digest.projectUpdates.forEach(u => {
      const status = u.status && u.status !== 'null' ? ` [${u.status}]` : ''
      lines.push(`  ${u.name}${status}: ${u.note}`)
    })
  }
  return lines.join('\n')
}

export async function POST(req) {
  const key = process.env.ANTHROPIC_API_KEY
  if (!key) return NextResponse.json({ error: 'ANTHROPIC_API_KEY not configured' }, { status: 503 })

  try {
    const body = await req.json()
    const { transcript, title = 'Meeting', analystIds = [], saveMeeting = false, applyUpdates = false } = body

    if (!transcript) return NextResponse.json({ error: 'transcript is required' }, { status: 400 })

    // Fetch full team context
    const [analysts, projects, meetings, todos] = await Promise.all([
      prisma.analyst.findMany({ include: { notes: { orderBy: { createdAt: 'desc' }, take: 5 } }, orderBy: { name: 'asc' } }),
      prisma.project.findMany({ include: { analysts: { include: { analyst: true } } }, orderBy: { updatedAt: 'desc' } }),
      prisma.meeting.findMany({ include: { analysts: { include: { analyst: true } } }, orderBy: { date: 'desc' }, take: 20 }),
      prisma.todo.findMany({ where: { done: false }, include: { analyst: true }, orderBy: { createdAt: 'desc' } }),
    ])

    const analystContext = analysts.map(a => {
      const notes = a.notes.map(n =>
        `    [${new Date(n.createdAt).toLocaleDateString()}] (${n.mood === 'h' ? 'positive' : n.mood === 'l' ? 'concern' : 'neutral'}): ${n.text}`
      ).join('\n')
      return `- ${a.name} (id:${a.id}, mood:${MOOD_LABEL[a.mood] || 'Steady'})${a.pending ? ' [PENDING]' : ''}${notes ? '\n  Notes:\n' + notes : ''}`
    }).join('\n')

    const projectContext = projects.map(p => {
      const names = p.analysts.map(pa => pa.analyst?.name).filter(Boolean).join(', ')
      return `- ${p.name} (id:${p.id}, status:${p.status})${names ? ' — ' + names : ''}`
    }).join('\n')

    const meetingContext = meetings.slice(0, 15).map(m => {
      const names = m.analysts.map(ma => ma.analyst?.name).filter(Boolean).join(', ')
      return `- [${new Date(m.date).toLocaleDateString()}] "${m.title}"${names ? ' with ' + names : ''}: ${m.notes?.slice(0, 200) || ''}...`
    }).join('\n')

    const todoContext = todos.map(t =>
      `- ${t.text}${t.analyst ? ' [re: ' + t.analyst.name + ']' : ''} (${t.priority})`
    ).join('\n')

    const fullContext = `TEAM:\n${analystContext || 'None'}\n\nPROJECTS:\n${projectContext || 'None'}\n\nRECENT MEETINGS:\n${meetingContext || 'None'}\n\nOPEN TODOS:\n${todoContext || 'None'}`

    const client = new Anthropic({ apiKey: key })
    const response = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 2000,
      messages: [{
        role: 'user',
        content: `You are a management assistant. The manager reading this IS the person who ran this meeting. Write everything directly to them (use "you", never their name).

FULL TEAM CONTEXT:
${fullContext}

MEETING TRANSCRIPT/NOTES:
"${transcript}"

Return ONLY valid JSON (no markdown fences):
{
  "analystUpdates": [{ "id": "id_from_context", "name": "first name", "note": "1-2 sentence summary", "mood": "h|m|l|null" }],
  "projectUpdates": [{ "id": "id_or_null", "name": "project name", "status": "active|review|done|blocked|null", "note": "what was said" }],
  "flags": ["urgent fact-based statements, e.g. 'Jade has been blocked 3 meetings in a row'"],
  "todos": ["direct imperatives: 'Follow up with...', 'Schedule...', 'Review...' — never mention the manager by name"]
}
Rules: only include entries with clear signal. Return empty arrays if nothing found.`
      }],
    })

    const raw = response.content[0].text.trim()
      .replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '')
    const digest = JSON.parse(raw)

    const now = new Date()
    let meetingId = null

    // Save meeting to DB if requested
    if (saveMeeting) {
      const meeting = await prisma.meeting.create({
        data: {
          title,
          date: now,
          notes: transcript,
          digest: 0,
          // Always store digest as pending so user can review in the app
          pendingDigest: applyUpdates ? null : digest,
          analysts: { create: analystIds.map(id => ({ analystId: id })) },
        },
      })
      meetingId = meeting.id
    }

    // Apply digest updates to DB if requested
    if (applyUpdates) {
      const ops = []

      ;(digest.analystUpdates || []).forEach(u => {
        const analyst = analysts.find(a => a.id === u.id) ||
          analysts.find(a => a.name.toLowerCase().includes(u.name?.toLowerCase()))
        if (!analyst) return
        if (u.mood && u.mood !== 'null') {
          ops.push(prisma.analyst.update({ where: { id: analyst.id }, data: { mood: u.mood } }))
        }
        if (u.note) {
          ops.push(prisma.note.create({
            data: { text: u.note, mood: u.mood || 'm', source: 'digest', meetingTitle: title, analystId: analyst.id },
          }))
        }
      })

      ;(digest.projectUpdates || []).forEach(u => {
        const project = projects.find(p => p.id === u.id) ||
          projects.find(p => p.name.toLowerCase().includes(u.name?.toLowerCase()))
        if (!project) return
        const data = {}
        if (u.status && u.status !== 'null') data.status = u.status
        if (u.note) data.notes = (project.notes ? project.notes + '\n' : '') + u.note
        if (Object.keys(data).length > 0) {
          ops.push(prisma.project.update({ where: { id: project.id }, data }))
        }
      })

      ;(digest.todos || []).forEach(t => {
        ops.push(prisma.todo.create({ data: { text: t, priority: 'normal' } }))
      })

      // Flags: save as concern notes under matched analysts, not todos
      ;(digest.flags || []).forEach(f => {
        // Try to find the analyst mentioned in the flag text
        const mentionedAnalyst = analysts.find(a =>
          f.toLowerCase().includes(a.name.toLowerCase().split(' ')[0])
        )
        if (mentionedAnalyst) {
          ops.push(prisma.note.create({
            data: { text: `⚠️ ${f}`, mood: 'l', source: 'digest', meetingTitle: title, analystId: mentionedAnalyst.id },
          }))
        } else {
          // No analyst match — fall back to high-priority todo
          ops.push(prisma.todo.create({ data: { text: f, priority: 'high' } }))
        }
      })

      await Promise.all(ops)
    }

    return NextResponse.json({
      digest,
      emailHtml: buildEmailHtml(title, digest, now),
      emailText: buildEmailText(title, digest, now),
      meetingId,
      appliedUpdates: applyUpdates,
    })
  } catch (e) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
