import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { prisma } from '@/lib/prisma'

/**
 * GET /api/n8n/weekly-summary
 *
 * Call from n8n on a weekly schedule (no body needed).
 * Returns a readable weekly briefing for Avi Lurie plus a formatted email.
 *
 * Returns:
 * {
 *   "summary": "plain prose weekly briefing",
 *   "emailHtml": "<html>...",
 *   "emailText": "plain text version"
 * }
 */

const MOOD_LABEL = { h: 'Thriving', m: 'Steady', l: 'Needs Attention' }

function buildWeeklyEmailHtml(summary, dateRange, data) {
  const { analysts, todos, projects, meetings } = data

  // Team mood section
  const thriving = analysts.filter(a => a.mood === 'h' && !a.pending)
  const needsAttention = analysts.filter(a => a.mood === 'l' && !a.pending)
  const steady = analysts.filter(a => a.mood === 'm' && !a.pending)

  const moodHtml = `
    <h2 style="color:#374151;font-size:16px;margin:24px 0 8px">Team Mood</h2>
    ${thriving.length > 0 ? `<div style="margin-bottom:8px"><span style="color:#16a34a;font-weight:600">Thriving:</span> <span style="color:#374151">${thriving.map(a => a.name).join(', ')}</span></div>` : ''}
    ${steady.length > 0 ? `<div style="margin-bottom:8px"><span style="color:#6b7280;font-weight:600">Steady:</span> <span style="color:#374151">${steady.map(a => a.name).join(', ')}</span></div>` : ''}
    ${needsAttention.length > 0 ? `<div style="margin-bottom:8px"><span style="color:#dc2626;font-weight:600">Needs Attention:</span> <span style="color:#374151">${needsAttention.map(a => a.name).join(', ')}</span></div>` : ''}`

  // Flags to watch (notes with mood 'l' from this week)
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  const recentConcernNotes = analysts.flatMap(a =>
    (a.notes || [])
      .filter(n => n.mood === 'l' && new Date(n.createdAt) >= sevenDaysAgo)
      .map(n => ({ analyst: a.name, text: n.text }))
  )

  const flagsHtml = recentConcernNotes.length > 0 ? `
    <h2 style="color:#dc2626;font-size:16px;margin:24px 0 8px">Flags to Watch</h2>
    <ul style="margin:0;padding-left:20px">
      ${recentConcernNotes.map(n => `<li style="margin-bottom:6px;color:#374151"><strong>${n.analyst}:</strong> ${n.text}</li>`).join('')}
    </ul>` : ''

  // Open action items
  const todosHtml = todos.length > 0 ? `
    <h2 style="color:#1d4ed8;font-size:16px;margin:24px 0 8px">Open Action Items</h2>
    <ul style="margin:0;padding-left:20px">
      ${todos.slice(0, 15).map(t => `<li style="margin-bottom:6px;color:#374151">${t.analyst ? `<strong>${t.analyst.name}:</strong> ` : ''}${t.text} <span style="font-size:12px;color:#9ca3af">(${t.priority})</span></li>`).join('')}
      ${todos.length > 15 ? `<li style="color:#9ca3af;font-size:13px">…and ${todos.length - 15} more</li>` : ''}
    </ul>` : ''

  // Project status
  const projectHtml = projects.length > 0 ? `
    <h2 style="color:#374151;font-size:16px;margin:24px 0 8px">Projects</h2>
    ${projects.map(p => {
      const statusColor = p.status === 'blocked' ? '#dc2626' : p.status === 'done' ? '#16a34a' : p.status === 'review' ? '#7c3aed' : '#1d4ed8'
      const names = p.analysts.map(pa => pa.analyst?.name).filter(Boolean).join(', ')
      return `<div style="background:#f9fafb;border-radius:8px;padding:10px 14px;margin-bottom:8px">
        <div style="font-weight:600;color:#111827">${p.name} <span style="font-size:12px;color:${statusColor};font-weight:400">[${p.status}]</span>${names ? `<span style="font-size:12px;color:#6b7280;font-weight:400"> — ${names}</span>` : ''}</div>
      </div>`
    }).join('')}` : ''

  // AI summary section
  const summaryHtml = `
    <h2 style="color:#374151;font-size:16px;margin:24px 0 8px">Weekly Briefing</h2>
    <div style="background:#f9fafb;border-radius:8px;padding:16px;color:#374151;font-size:14px;line-height:1.6;white-space:pre-wrap">${summary}</div>`

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#111827">
  <div style="border-bottom:2px solid #e5e7eb;padding-bottom:16px;margin-bottom:8px">
    <h1 style="margin:0;font-size:22px;color:#111827">Weekly Team Digest</h1>
    <div style="color:#6b7280;font-size:14px;margin-top:4px">${dateRange} · ${meetings.length} meeting${meetings.length !== 1 ? 's' : ''} this week</div>
  </div>
  ${moodHtml}
  ${flagsHtml}
  ${summaryHtml}
  ${todosHtml}
  ${projectHtml}
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af">
    Generated by My Team Hub · Weekly Summary
  </div>
</body>
</html>`
}

function buildWeeklyEmailText(summary, dateRange, data) {
  const { analysts, todos, projects, meetings } = data
  const lines = [`WEEKLY TEAM DIGEST — ${dateRange}`, `${meetings.length} meeting(s) this week`, '']

  const thriving = analysts.filter(a => a.mood === 'h' && !a.pending)
  const needsAttention = analysts.filter(a => a.mood === 'l' && !a.pending)
  const steady = analysts.filter(a => a.mood === 'm' && !a.pending)

  lines.push('TEAM MOOD')
  if (thriving.length > 0) lines.push(`  Thriving: ${thriving.map(a => a.name).join(', ')}`)
  if (steady.length > 0) lines.push(`  Steady: ${steady.map(a => a.name).join(', ')}`)
  if (needsAttention.length > 0) lines.push(`  Needs Attention: ${needsAttention.map(a => a.name).join(', ')}`)
  lines.push('')

  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  const recentConcernNotes = analysts.flatMap(a =>
    (a.notes || [])
      .filter(n => n.mood === 'l' && new Date(n.createdAt) >= sevenDaysAgo)
      .map(n => ({ analyst: a.name, text: n.text }))
  )
  if (recentConcernNotes.length > 0) {
    lines.push('FLAGS TO WATCH')
    recentConcernNotes.forEach(n => lines.push(`  • ${n.analyst}: ${n.text}`))
    lines.push('')
  }

  lines.push('WEEKLY BRIEFING')
  lines.push(summary)
  lines.push('')

  if (todos.length > 0) {
    lines.push('OPEN ACTION ITEMS')
    todos.slice(0, 15).forEach(t => {
      lines.push(`  • ${t.analyst ? t.analyst.name + ': ' : ''}${t.text} (${t.priority})`)
    })
    if (todos.length > 15) lines.push(`  …and ${todos.length - 15} more`)
    lines.push('')
  }

  if (projects.length > 0) {
    lines.push('PROJECTS')
    projects.forEach(p => {
      const names = p.analysts.map(pa => pa.analyst?.name).filter(Boolean).join(', ')
      lines.push(`  ${p.name} [${p.status}]${names ? ' — ' + names : ''}`)
    })
  }

  return lines.join('\n')
}

export async function GET() {
  const key = process.env.ANTHROPIC_API_KEY
  if (!key) return NextResponse.json({ error: 'ANTHROPIC_API_KEY not configured' }, { status: 503 })

  try {
    const now = new Date()
    const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

    const [analysts, todos, projects, meetings] = await Promise.all([
      // Analysts with their last 10 notes
      prisma.analyst.findMany({
        include: {
          notes: { orderBy: { createdAt: 'desc' }, take: 10 },
        },
        orderBy: { name: 'asc' },
      }),
      // All open todos
      prisma.todo.findMany({
        where: { done: false },
        include: { analyst: true },
        orderBy: [{ priority: 'asc' }, { createdAt: 'desc' }],
      }),
      // All projects
      prisma.project.findMany({
        include: { analysts: { include: { analyst: true } } },
        orderBy: { updatedAt: 'desc' },
      }),
      // Meetings from the last 7 days with analysts
      prisma.meeting.findMany({
        where: { date: { gte: sevenDaysAgo } },
        include: { analysts: { include: { analyst: true } } },
        orderBy: { date: 'desc' },
      }),
    ])

    // Build context for the prompt
    const analystContext = analysts.map(a => {
      const moodLabel = MOOD_LABEL[a.mood] || 'Steady'
      const recentNotes = a.notes.map(n => {
        const daysAgo = Math.floor((now - new Date(n.createdAt)) / (1000 * 60 * 60 * 24))
        return `    [${daysAgo}d ago] (${n.mood === 'h' ? 'positive' : n.mood === 'l' ? 'concern' : 'neutral'}): ${n.text}`
      }).join('\n')
      return `- ${a.name} (${a.role}, mood: ${moodLabel})${a.pending ? ' [PENDING]' : ''}${recentNotes ? '\n  Recent notes:\n' + recentNotes : ''}`
    }).join('\n')

    const meetingContext = meetings.map(m => {
      const names = m.analysts.map(ma => ma.analyst?.name).filter(Boolean).join(', ')
      return `- [${new Date(m.date).toLocaleDateString()}] "${m.title}"${names ? ' with ' + names : ''}: ${m.notes?.slice(0, 300) || ''}...`
    }).join('\n')

    const todoContext = todos.map(t =>
      `- ${t.text}${t.analyst ? ' [re: ' + t.analyst.name + ']' : ''} (${t.priority} priority)`
    ).join('\n')

    const projectContext = projects.map(p => {
      const names = p.analysts.map(pa => pa.analyst?.name).filter(Boolean).join(', ')
      return `- ${p.name} (status: ${p.status})${names ? ' — ' + names : ''}${p.notes ? '\n  Notes: ' + p.notes.slice(0, 200) : ''}`
    }).join('\n')

    // Date range label
    const dateRangeLabel = `${sevenDaysAgo.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`

    const prompt = `You are summarizing the past week for Avi Lurie, Team Lead. Write directly to them using "you". This is a private management briefing, so be candid and direct.

TEAM MEMBERS (with recent notes):
${analystContext || 'None'}

MEETINGS THIS WEEK (${meetings.length}):
${meetingContext || 'No meetings this week'}

OPEN ACTION ITEMS (${todos.length} total):
${todoContext || 'None'}

PROJECTS:
${projectContext || 'None'}

Write a clear, readable weekly briefing in plain prose (not JSON, not bullet points — flowing paragraphs). Cover:
1. Mood trends — who improved, who declined, who to keep an eye on
2. Unresolved flags — any team members with recent concern notes (mood: l) that need your attention
3. Meeting activity this week — what was discussed, any patterns
4. Open action items — highlight high priority ones and any that seem overdue
5. Project status changes or risks

Keep it concise but complete. Write as if speaking directly to Avi: use "you", "your team", etc. Be specific with names and details. Don't pad with generic advice.`

    const client = new Anthropic({ apiKey: key })
    const response = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }],
    })

    const summary = response.content[0].text.trim()
    const emailData = { analysts, todos, projects, meetings }

    return NextResponse.json({
      summary,
      emailHtml: buildWeeklyEmailHtml(summary, dateRangeLabel, emailData),
      emailText: buildWeeklyEmailText(summary, dateRangeLabel, emailData),
    })
  } catch (e) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
